### ISSUE TITLE
Will it display the number of unread messages?

### ISSUE THREAD

**Issue by Aleck85** [YannBertrand/FacebookNotifier#1]
Will it display the number of unread messages?

**Comment by yannbertrand** [comment]
No it won't.

It's just supposed to display "notifications".

Another extension displaying unread messages would be a good idea though 😉

**Comment by Aleck85** [comment]
It's a pity! Having two extensions for the same site is not a good idea.

**Comment by yannbertrand** [comment]
I personally do not need this feature. But you can fork the project if you want something else 😄
